{ config, pkgs, lib, inputs, userConfig, ... }:

let
  # herdr is not in our pinned nixpkgs yet, so it comes from its own flake,
  # pinned by tag in flake.nix.
  herdrPkg = inputs.herdr.packages.${pkgs.stdenv.hostPlatform.system}.default;

  sessionizer = "${config.home.homeDirectory}/.local/scripts/herdr-sessionizer";

  palette = import ../lib/palette.nix;
in
{
  home.packages = [ herdrPkg ];

  # herdr — agent-aware terminal multiplexer, configured to mirror the tmux
  # setup above (programs.tmux + dotfiles/tmux/tmux.local.conf).
  #
  # Model mapping:
  #   tmux session (one per project, via sessionizer) -> herdr workspace
  #   tmux window                                     -> herdr tab
  #   tmux pane                                       -> herdr pane
  #
  # Generated by nix rather than symlinked from dotfiles/ because
  # [terminal].default_shell needs the interpolated zsh store path: herdr does
  # not expand `~`, and macOS $SHELL is /bin/zsh (the same reason
  # programs.tmux pins shell/default-command).
  #
  # After editing: home-manager switch, then `herdr server reload-config`
  # (or prefix+r inside herdr).
  xdg.configFile."herdr/config.toml".text = ''
    onboarding = false

    # ============================================= #
    # Terminal / shell                              #
    # ============================================= #

    [terminal]
    # Same pin as programs.tmux: macOS $SHELL is /bin/zsh, we want the nix zsh.
    default_shell = "${pkgs.zsh}/bin/zsh"

    # "auto" = login shells on macOS. tmux ran non-login interactive shells;
    # switch to "non_login" if login-shell PATH reordering (path_helper) bites.
    shell_mode = "auto"

    # tmux equivalent: splits/new windows used -c "#{pane_current_path}"
    new_cwd = "follow"

    # ============================================= #
    # Theme — Catppuccin Macchiato                  #
    # ============================================= #

    [theme]
    # herdr's built-in catppuccin is Mocha; the overrides below convert it to
    # Macchiato, matching tmux.local.conf, ghostty and nvim.
    name = "catppuccin"

    [theme.custom]
    panel_bg    = "${palette.mantle}" # mantle — sidebar, recessed from pane bg
    surface_dim = "${palette.surface0}" # surface0 — tmux thm_gray
    text        = "${palette.text}" # tmux thm_fg
    subtext0    = "${palette.subtext0}"
    overlay0    = "${palette.overlay0}"
    overlay1    = "${palette.overlay1}"
    accent      = "${palette.blue}" # tmux thm_blue — pane-active-border
    blue        = "${palette.blue}"
    mauve       = "${palette.mauve}" # tmux thm_magenta
    red         = "${palette.red}"
    green       = "${palette.green}"
    yellow      = "${palette.yellow}"
    peach       = "${palette.peach}" # tmux thm_orange
    teal        = "${palette.teal}"

    # ============================================= #
    # Keybindings                                   #
    # ============================================= #

    [keys]
    # tmux: unbind C-b; set -g prefix C-a
    prefix = "ctrl+a"

    # --- Panes: focus ---------------------------------------------
    # tmux bound both `prefix h/j/k/l` and bare `M-h/j/k/l` (bind -n).
    # ctrl+h/j/k/l stays unbound so nvim's vim-tmux-navigator still gets it.
    focus_pane_left  = ["prefix+h", "alt+h"]
    focus_pane_down  = ["prefix+j", "alt+j"]
    focus_pane_up    = ["prefix+k", "alt+k"]
    focus_pane_right = ["prefix+l", "alt+l"]
    cycle_pane_next     = "prefix+tab"
    cycle_pane_previous = "prefix+shift+tab"

    # --- Panes: swap (tmux swap-pane, vi-flavored) ----------------
    swap_pane_left  = "prefix+shift+h"
    swap_pane_down  = "prefix+shift+j"
    swap_pane_up    = "prefix+shift+k"
    swap_pane_right = "prefix+shift+l"

    # --- Panes: split / close / zoom ------------------------------
    # tmux: bind | split-window -h (side by side) -> split_vertical
    #       bind - split-window -v (stacked)      -> split_horizontal
    # Verified against herdr's layout API: split_vertical => direction "right".
    split_vertical   = ["prefix+|", "prefix+v"]
    split_horizontal = ["prefix+minus", "prefix+s"]
    close_pane  = "prefix+x"
    zoom        = "prefix+z"
    rename_pane = "prefix+shift+p"
    # tmux had no resize binding; moved off prefix+r so `r` reloads like tmux.
    resize_mode = "prefix+shift+r"

    # --- Tabs (tmux windows) --------------------------------------
    new_tab      = "prefix+c"
    next_tab     = "prefix+n"
    previous_tab = "prefix+p"
    rename_tab   = "prefix+shift+t"
    close_tab    = "prefix+shift+x"
    # tmux: bind -n M-1..M-9 select-window -t N, plus 1-based indexing
    switch_tab = ["prefix+1..9", "alt+1..9"]

    # --- Workspaces (tmux sessions) -------------------------------
    workspace_picker   = "prefix+w"
    goto               = "prefix+g"
    new_workspace      = "prefix+shift+n"
    rename_workspace   = "prefix+shift+w"
    close_workspace    = "prefix+shift+d"
    switch_workspace   = "prefix+shift+1..9"
    previous_workspace = "prefix+comma"
    next_workspace     = "prefix+."
    new_worktree       = "prefix+shift+g"

    # --- Copy / scrollback (tmux vi copy-mode) --------------------
    # tmux: set -g mode-keys vi; prefix+[ entered copy mode.
    copy_mode       = "prefix+["
    edit_scrollback = "prefix+e"

    # --- Session / misc -------------------------------------------
    # tmux: unbind r; bind r source-file ~/.config/tmux/tmux.conf
    reload_config  = "prefix+r"
    detach         = "prefix+q"
    help           = "prefix+?"
    settings       = "prefix+shift+s"
    toggle_sidebar = "prefix+b"
    open_notification_target = "prefix+o"

    # --- Navigate-mode movement (vi keys) -------------------------
    navigate_workspace_up   = "up"
    navigate_workspace_down = "down"
    navigate_pane_left  = "h"
    navigate_pane_down  = "j"
    navigate_pane_up    = "k"
    navigate_pane_right = "l"

    # --- Sessionizer ----------------------------------------------
    # tmux: bind-key -r f new-window "~/.local/scripts/tmux-sessionizer"
    # A popup instead of a new tab, so fzf overlays the current layout.
    [[keys.command]]
    key = "prefix+f"
    type = "popup"
    command = "${sessionizer}"
    description = "sessionizer: fzf a project -> focus/create workspace"
    width = "80%"
    height = "80%"

    # ============================================= #
    # UI                                            #
    # ============================================= #

    [ui]
    # tmux: set -g mouse on
    mouse_capture = true
    copy_on_select = true
    mouse_scroll_lines = 3

    # tmux: set-option -g status-position top
    tab_bar_position = "top"

    accent = "${palette.blue}"

    # tmux new-window took no name prompt; keep creation instant.
    prompt_new_tab_name = false
    prompt_new_workspace_name = false
    confirm_close = true

    # tmux: pane-border-style / pane-active-border-style
    pane_borders = true
    pane_gaps = true
    pane_scrollbars = true

    sidebar_width = 26
    agent_panel_sort = "spaces"

    [ui.toast]
    delivery = "herdr"
    delay_seconds = 1

    [ui.sound]
    enabled = true

    # ============================================= #
    # Persistence (tmux-resurrect + tmux-continuum) #
    # ============================================= #

    [session]
    # resurrect/continuum restored sessions across restarts. herdr's server
    # keeps workspaces/tabs/panes alive itself; this restores agent
    # conversations too.
    resume_agents_on_restore = true

    [experimental]
    # Closest analogue to resurrect's saved pane contents.
    pane_history = true

    [advanced]
    # tmux: set -g history-limit 10000
    scrollback_limit_bytes = 10000000
  '';

  # herdr sessionizer (generated from userConfig.sessionizerPaths, exactly like
  # the tmux one). Focuses the workspace for a project, creating it if needed.
  # Works from a herdr popup (prefix+f) and from a bare shell, where it
  # starts the server and attaches afterwards.
  home.file.".local/scripts/herdr-sessionizer" = {
    executable = true;
    text = ''
      #!/usr/bin/env bash

      herdr=${herdrPkg}/bin/herdr
      jq=${pkgs.jq}/bin/jq

      if [[ $# -eq 1 ]]; then
          selected=$1
      else
          selected=$(find ${lib.concatStringsSep " " userConfig.sessionizerPaths} -mindepth 1 -maxdepth 1 -type d 2>/dev/null | ${pkgs.fzf}/bin/fzf)
      fi

      if [[ -z $selected ]]; then
          exit 0
      fi

      selected_name=$(basename "$selected" | tr '. ' '_')

      # Set Ghostty tab title to the workspace name
      printf '\e]1;%s\a' "$selected_name"

      server_running() {
          "$herdr" status server 2>/dev/null | grep -q '^status: running'
      }

      # Popups and panes get HERDR_* env; a bare shell does not.
      inside_herdr=0
      if [[ -n $HERDR_SOCKET_PATH ]] || [[ -n $HERDR_PANE_ID ]]; then
          inside_herdr=1
      fi

      if ! server_running; then
          if [[ $inside_herdr -eq 1 ]]; then
              echo "herdr-sessionizer: herdr server is not reachable" >&2
              exit 1
          fi
          nohup "$herdr" server >/dev/null 2>&1 &
          for _ in $(seq 1 40); do
              server_running && break
              sleep 0.25
          done
          if ! server_running; then
              echo "herdr-sessionizer: failed to start herdr server" >&2
              exit 1
          fi
      fi

      workspace_id=$("$herdr" workspace list 2>/dev/null \
          | "$jq" -r --arg label "$selected_name" \
              '.result.workspaces[]? | select(.label == $label) | .workspace_id' \
          | head -n1)

      if [[ -n $workspace_id ]]; then
          "$herdr" workspace focus "$workspace_id" >/dev/null
      else
          "$herdr" workspace create --cwd "$selected" --label "$selected_name" --focus >/dev/null
      fi

      # Launched from a plain shell: attach to the session we just prepared.
      if [[ $inside_herdr -eq 0 ]]; then
          exec "$herdr"
      fi
    '';
  };
}
